import 'dotenv/config';
import Fastify from 'fastify';
import cookie from '@fastify/cookie';
import helmet from '@fastify/helmet';
import rateLimit from '@fastify/rate-limit';
import pg from 'pg';
import twilio from 'twilio';
import { fetch,ProxyAgent } from 'undici';
import { createHash,randomUUID } from 'node:crypto';
import { DateTime } from 'luxon';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { security,Vault } from './security.js';
import { hashPassword,verifyPassword,validatePassword,signAccessToken,signRefreshToken,verifyJwt,hashToken } from './auth.js';
import { backtest,classify,defaultRisk,engineerFeatures,optimizePortfolio,sizePosition,syntheticCandles,walkForward } from './quant-engine.js';

const required=['APP_ORIGIN','DATABASE_URL','COOKIE_SECRET','JWT_SECRET','TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_VERIFY_SERVICE_SID','DATA_KEYRING_JSON','ACTIVE_DATA_KEY_VERSION','BROKER_CONFIG_JSON'] as const;
for(const key of required)if(!process.env[key])throw new Error(`Missing ${key}`);
if(Buffer.from(process.env.JWT_SECRET!,'base64').length<32)throw new Error('JWT_SECRET must contain at least 32 random bytes encoded as base64');
const prod=process.env.NODE_ENV==='production'; if(prod&&!process.env.BROKER_HTTPS_PROXY)throw new Error('Static-IP BROKER_HTTPS_PROXY required');
const origin=process.env.APP_ORIGIN!.replace(/\/$/,'');
const db=new pg.Pool({connectionString:process.env.DATABASE_URL,max:10});
const sms=twilio(process.env.TWILIO_ACCOUNT_SID,process.env.TWILIO_AUTH_TOKEN);
const vault=new Vault(JSON.parse(process.env.DATA_KEYRING_JSON!),process.env.ACTIVE_DATA_KEY_VERSION!);
const brokerConfigs=JSON.parse(process.env.BROKER_CONFIG_JSON!) as Record<string,{clientId:string;clientSecret:string;authorizeUrl:string;tokenUrl:string;scopes:string[]}>;
const dispatcher=process.env.BROKER_HTTPS_PROXY?new ProxyAgent(process.env.BROKER_HTTPS_PROXY):undefined;
const app=Fastify({logger:{redact:['req.headers.authorization','req.headers.cookie','res.headers.set-cookie','body.password','body.newPassword','body.code','body.adminBootstrapToken','*.access_token','*.clientSecret','*.mobile']},bodyLimit:32768});
await app.register(helmet,{contentSecurityPolicy:{directives:{defaultSrc:["'self'"],styleSrc:["'self'","'unsafe-inline'"],scriptSrc:["'self'","'unsafe-inline'"]}}});
await app.register(cookie,{secret:process.env.COOKIE_SECRET!});
await app.register(rateLimit,{max:60,timeWindow:'1 minute'});
app.addHook('onRequest',async(req,reply)=>{if(prod&&['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.headers.origin!==origin)return reply.code(403).send({error:'bad_origin'});});

type AppUser={id:string;email:string;role:string};
function setAuthCookies(reply:any,access:string,refresh:string){const base={httpOnly:true,secure:prod,sameSite:'strict' as const,path:'/'};reply.setCookie('gnk_access',access,{...base,maxAge:900});reply.setCookie('gnk_refresh',refresh,{...base,maxAge:2592000});}
async function issueTokens(user:AppUser,reply:any,familyId=randomUUID(),cx:pg.Pool|pg.PoolClient=db){const jti=randomUUID();const access=await signAccessToken(user);const refresh=await signRefreshToken(user.id,jti,familyId);await cx.query(`INSERT INTO refresh_tokens(id,user_id,token_hash,family_id,expires_at) VALUES($1,$2,$3,$4,now()+interval '30 days')`,[jti,user.id,hashToken(refresh),familyId]);setAuthCookies(reply,access,refresh);return{accessToken:access,tokenType:'Bearer',expiresIn:900,user:{id:user.id,email:user.email,role:user.role}};}
async function requireUser(req:any,reply:any){const bearer=req.headers.authorization?.match(/^Bearer (.+)$/i)?.[1];const token=bearer??req.cookies.gnk_access;if(!token)return reply.code(401).send({error:'authentication_required'});try{const {payload}=await verifyJwt(token,'gnkalgo-api');if(payload.token_use!=='access'||!payload.sub)throw new Error();const q=await db.query(`SELECT id,email,role FROM users WHERE id=$1 AND disabled_at IS NULL`,[payload.sub]);if(!q.rowCount)throw new Error();req.user=q.rows[0];}catch{return reply.code(401).send({error:'invalid_or_expired_token'});}}
const normalizeEmail=(v:unknown)=>typeof v==='string'?v.trim().toLowerCase():'';
const mobileRe=/^\+[1-9]\d{7,14}$/;

app.post('/api/v1/auth/otp/request',{config:{rateLimit:{max:5,timeWindow:'15 minutes'}}},async(req:any,reply)=>{const mobile=req.body?.mobile,purpose=req.body?.purpose??'register';if(!mobileRe.test(mobile)||purpose!=='register')return reply.code(400).send({error:'invalid_input'});await sms.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID!).verifications.create({to:mobile,channel:'sms'});await db.query(`INSERT INTO otp_attempts(mobile_hash,expires_at,purpose) VALUES($1,now()+interval '10 minutes','register')`,[security.sha256(mobile)]);return reply.code(202).send({ok:true});});
app.post('/api/v1/auth/otp/verify',{config:{rateLimit:{max:10,timeWindow:'15 minutes'}}},async(req:any,reply)=>{const {mobile,code}=req.body??{};if(!mobileRe.test(mobile)||!/^\d{4,10}$/.test(code))return reply.code(400).send({error:'invalid_input'});const a=await db.query(`UPDATE otp_attempts SET attempt_count=attempt_count+1 WHERE id=(SELECT id FROM otp_attempts WHERE mobile_hash=$1 AND purpose='register' AND consumed_at IS NULL AND expires_at>now() AND attempt_count<5 ORDER BY created_at DESC LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING id`,[security.sha256(mobile)]);if(!a.rowCount)return reply.code(429).send({error:'otp_unavailable'});const check=await sms.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID!).verificationChecks.create({to:mobile,code});if(check.status!=='approved')return reply.code(401).send({error:'invalid_otp'});const token=security.randomToken();await db.query(`WITH consumed AS (UPDATE otp_attempts SET consumed_at=now() WHERE id=$1) INSERT INTO mobile_verification_grants(mobile,token_hash,expires_at) VALUES($2,$3,now()+interval '10 minutes')`,[a.rows[0].id,mobile,hashToken(token)]);return{ok:true,mobileVerificationToken:token,expiresIn:600};});

app.post('/api/v1/auth/register',{config:{rateLimit:{max:5,timeWindow:'1 hour'}}},async(req:any,reply)=>{const email=normalizeEmail(req.body?.email),displayName=typeof req.body?.displayName==='string'?req.body.displayName.trim():'';const password=req.body?.password,grant=req.body?.mobileVerificationToken,adminToken=req.body?.adminBootstrapToken;const passwordError=validatePassword(password);if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||displayName.length<2||displayName.length>100||passwordError||typeof grant!=='string')return reply.code(400).send({error:passwordError??'invalid_registration'});const wantsAdmin=email===normalizeEmail(process.env.ADMIN_EMAIL);if(wantsAdmin&&(!process.env.ADMIN_BOOTSTRAP_TOKEN||adminToken!==process.env.ADMIN_BOOTSTRAP_TOKEN))return reply.code(403).send({error:'admin_bootstrap_token_required'});const cx=await db.connect();try{await cx.query('BEGIN');const g=await cx.query(`UPDATE mobile_verification_grants SET consumed_at=now() WHERE token_hash=$1 AND consumed_at IS NULL AND expires_at>now() RETURNING mobile`,[hashToken(grant)]);if(!g.rowCount){await cx.query('ROLLBACK');return reply.code(400).send({error:'invalid_mobile_verification'});}const existing=await cx.query(`SELECT 1 FROM users WHERE lower(email)=lower($1) UNION ALL SELECT 1 FROM user_identities WHERE kind='mobile' AND provider_subject=$2`,[email,g.rows[0].mobile]);if(existing.rowCount){await cx.query('ROLLBACK');return reply.code(409).send({error:'account_already_exists'});}const u=(await cx.query(`INSERT INTO users(email,display_name,role) VALUES($1,$2,$3) RETURNING id,email,role`,[email,displayName,wantsAdmin?'admin':'user'])).rows[0];await cx.query(`INSERT INTO user_credentials(user_id,password_hash) VALUES($1,$2)`,[u.id,await hashPassword(password)]);await cx.query(`INSERT INTO user_identities(user_id,kind,provider_subject,verified_at) VALUES($1,'mobile',$2,now())`,[u.id,g.rows[0].mobile]);const result=await issueTokens(u,reply,randomUUID(),cx);await cx.query('COMMIT');return reply.code(201).send(result);}catch(e:any){await cx.query('ROLLBACK');if(e?.code==='23505')return reply.code(409).send({error:'account_already_exists'});throw e;}finally{cx.release();}});
app.post('/api/v1/auth/login',{config:{rateLimit:{max:10,timeWindow:'15 minutes'}}},async(req:any,reply)=>{const email=normalizeEmail(req.body?.email),password=req.body?.password;if(!email||typeof password!=='string')return reply.code(400).send({error:'invalid_input'});const q=await db.query(`SELECT u.id,u.email,u.role,c.password_hash,c.failed_attempts,c.locked_until FROM users u JOIN user_credentials c ON c.user_id=u.id WHERE lower(u.email)=lower($1) AND u.disabled_at IS NULL`,[email]);const row=q.rows[0];if(!row||row.locked_until&&new Date(row.locked_until)>new Date()||!await verifyPassword(password,row.password_hash)){if(row)await db.query(`UPDATE user_credentials SET failed_attempts=failed_attempts+1,locked_until=CASE WHEN failed_attempts+1>=5 THEN now()+interval '15 minutes' ELSE locked_until END WHERE user_id=$1`,[row.id]);return reply.code(401).send({error:'invalid_email_or_password'});}await db.query(`UPDATE user_credentials SET failed_attempts=0,locked_until=NULL WHERE user_id=$1`,[row.id]);return issueTokens(row,reply);});
app.post('/api/v1/auth/refresh',async(req:any,reply)=>{const token=req.cookies.gnk_refresh;if(!token)return reply.code(401).send({error:'refresh_required'});let payload:any;try{payload=(await verifyJwt(token,'gnkalgo-refresh')).payload;}catch{return reply.code(401).send({error:'invalid_refresh'});}const cx=await db.connect();try{await cx.query('BEGIN');const old=await cx.query(`SELECT * FROM refresh_tokens WHERE id=$1 FOR UPDATE`,[payload.jti]);if(!old.rowCount||!old.rows[0].token_hash.equals(hashToken(token))||old.rows[0].revoked_at||old.rows[0].consumed_at||new Date(old.rows[0].expires_at)<=new Date()){if(payload.family_id)await cx.query(`UPDATE refresh_tokens SET revoked_at=now() WHERE family_id=$1 AND revoked_at IS NULL`,[payload.family_id]);await cx.query('COMMIT');return reply.code(401).send({error:'refresh_reuse_or_expired'});}const u=(await cx.query(`SELECT id,email,role FROM users WHERE id=$1 AND disabled_at IS NULL`,[payload.sub])).rows[0];if(!u){await cx.query('ROLLBACK');return reply.code(401).send({error:'invalid_refresh'});}const result=await issueTokens(u,reply,payload.family_id,cx);await cx.query(`UPDATE refresh_tokens SET consumed_at=now(),replaced_by=(SELECT id FROM refresh_tokens WHERE family_id=$1 ORDER BY created_at DESC LIMIT 1) WHERE id=$2`,[payload.family_id,payload.jti]);await cx.query('COMMIT');return result;}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});
app.post('/api/v1/auth/logout',async(req:any,reply)=>{const token=req.cookies.gnk_refresh;if(token){try{const {payload}=await verifyJwt(token,'gnkalgo-refresh');if(payload.family_id)await db.query(`UPDATE refresh_tokens SET revoked_at=now() WHERE family_id=$1 AND revoked_at IS NULL`,[payload.family_id]);}catch{}}reply.clearCookie('gnk_access',{path:'/'});reply.clearCookie('gnk_refresh',{path:'/'});return{ok:true};});

app.post('/api/v1/auth/forgot-password',{config:{rateLimit:{max:5,timeWindow:'1 hour'}}},async(req:any,reply)=>{const email=normalizeEmail(req.body?.email);const q=await db.query(`SELECT u.id,i.provider_subject mobile FROM users u JOIN user_identities i ON i.user_id=u.id AND i.kind='mobile' WHERE lower(u.email)=lower($1) AND u.disabled_at IS NULL`,[email]);if(q.rowCount){await sms.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID!).verifications.create({to:q.rows[0].mobile,channel:'sms'});await db.query(`INSERT INTO password_reset_challenges(user_id,expires_at) VALUES($1,now()+interval '10 minutes')`,[q.rows[0].id]);}return reply.code(202).send({ok:true,message:'If the account exists, a reset code was sent to its verified mobile.'});});
app.post('/api/v1/auth/reset-password',{config:{rateLimit:{max:10,timeWindow:'1 hour'}}},async(req:any,reply)=>{const email=normalizeEmail(req.body?.email),code=req.body?.code,newPassword=req.body?.newPassword;const err=validatePassword(newPassword);if(!/^\d{4,10}$/.test(code??'')||err)return reply.code(400).send({error:err??'invalid_input'});const q=await db.query(`SELECT u.id,i.provider_subject mobile,c.id challenge_id,c.attempts FROM users u JOIN user_identities i ON i.user_id=u.id AND i.kind='mobile' JOIN LATERAL (SELECT * FROM password_reset_challenges WHERE user_id=u.id AND consumed_at IS NULL AND expires_at>now() ORDER BY created_at DESC LIMIT 1) c ON true WHERE lower(u.email)=lower($1)`,[email]);if(!q.rowCount||q.rows[0].attempts>=5)return reply.code(400).send({error:'invalid_or_expired_reset'});await db.query(`UPDATE password_reset_challenges SET attempts=attempts+1 WHERE id=$1`,[q.rows[0].challenge_id]);const check=await sms.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID!).verificationChecks.create({to:q.rows[0].mobile,code});if(check.status!=='approved')return reply.code(400).send({error:'invalid_or_expired_reset'});const cx=await db.connect();try{await cx.query('BEGIN');await cx.query(`UPDATE password_reset_challenges SET consumed_at=now() WHERE id=$1`,[q.rows[0].challenge_id]);await cx.query(`UPDATE user_credentials SET password_hash=$1,password_changed_at=now(),failed_attempts=0,locked_until=NULL,updated_at=now() WHERE user_id=$2`,[await hashPassword(newPassword),q.rows[0].id]);await cx.query(`UPDATE refresh_tokens SET revoked_at=now() WHERE user_id=$1 AND revoked_at IS NULL`,[q.rows[0].id]);await cx.query('COMMIT');reply.clearCookie('gnk_access',{path:'/'});reply.clearCookie('gnk_refresh',{path:'/'});return{ok:true};}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});
app.get('/api/v1/auth/me',{preHandler:requireUser},async(req:any)=>({user:req.user}));

const broker=(name:string)=>{if(!['dhan','fyers','zerodha','angelone','upstox'].includes(name)||!brokerConfigs[name])throw new Error('unsupported_or_disabled_broker');return brokerConfigs[name]!;};
app.get('/api/v1/auth/redirect/:broker',{preHandler:requireUser},async(req:any,reply)=>{const name=req.params.broker,c=broker(name),state=security.randomToken();await db.query(`INSERT INTO broker_oauth_states(user_id,broker,state_hash,expires_at) VALUES($1,$2,$3,now()+interval '10 minutes')`,[req.user.id,name,security.sha256(state)]);const u=new URL(c.authorizeUrl);u.searchParams.set(name==='zerodha'?'api_key':'client_id',c.clientId);if(name==='zerodha')u.searchParams.set('redirect_params',new URLSearchParams({state}).toString());else{u.searchParams.set('redirect_uri',`${origin}/api/v1/auth/callback/${name}`);u.searchParams.set('response_type','code');u.searchParams.set('state',state);if(c.scopes?.length)u.searchParams.set('scope',c.scopes.join(' '));}return reply.redirect(u.toString());});
app.get('/api/v1/auth/callback/:broker',async(req:any,reply)=>{const name=req.params.broker,c=broker(name),state=req.query.state??new URLSearchParams(req.query.redirect_params??'').get('state'),code=name==='zerodha'?req.query.request_token:req.query.code;if(!state||!code)return reply.code(400).send({error:'invalid_callback'});const cx=await db.connect();try{await cx.query('BEGIN');const s=await cx.query(`UPDATE broker_oauth_states SET consumed_at=now() WHERE state_hash=$1 AND broker=$2 AND consumed_at IS NULL AND expires_at>now() RETURNING user_id`,[security.sha256(state),name]);if(!s.rowCount){await cx.query('ROLLBACK');return reply.code(400).send({error:'invalid_or_expired_state'});}const f=new URLSearchParams();if(name==='zerodha'){f.set('api_key',c.clientId);f.set('request_token',code);f.set('checksum',createHash('sha256').update(c.clientId+code+c.clientSecret).digest('hex'));}else{Object.entries({code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:`${origin}/api/v1/auth/callback/${name}`,grant_type:'authorization_code'}).forEach(([k,v])=>f.set(k,v));}const response=await fetch(c.tokenUrl,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','accept':'application/json'},body:f,dispatcher});if(!response.ok)throw new Error(`broker_exchange_failed:${response.status}`);const raw:any=await response.json(),token=(raw.data??raw).access_token;if(typeof token!=='string')throw new Error('missing_access_token');const uid=s.rows[0].user_id,enc=vault.encrypt(token,`${uid}:${name}:access_token`);let expiry=DateTime.now().setZone('Asia/Kolkata').set({hour:15,minute:30,second:0,millisecond:0});if(expiry<=DateTime.now().setZone('Asia/Kolkata'))expiry=expiry.plus({days:1});await cx.query(`INSERT INTO user_broker_tokens(user_id,broker,client_id,encrypted_access_token,encryption_key_version,token_generated_at,session_expiry_timestamp) VALUES($1,$2,$3,$4,$5,now(),$6) ON CONFLICT(user_id,broker) DO UPDATE SET encrypted_access_token=excluded.encrypted_access_token,encryption_key_version=excluded.encryption_key_version,token_generated_at=now(),session_expiry_timestamp=excluded.session_expiry_timestamp,revoked_at=NULL,updated_at=now()`,[uid,name,c.clientId,enc.ciphertext,enc.keyVersion,expiry.toUTC().toJSDate()]);await cx.query('COMMIT');return reply.redirect(`${origin}/?connected=${name}`);}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});
app.post('/api/v1/trades/kill-switch',{preHandler:requireUser},async(req:any,reply)=>{if(req.body?.confirm!=='KILL')return reply.code(400).send({error:'confirmation_required'});const cx=await db.connect();try{await cx.query('BEGIN');await cx.query(`INSERT INTO trade_worker_state(user_id,enabled,reason) VALUES($1,false,'USER_KILL_SWITCH') ON CONFLICT(user_id) DO UPDATE SET enabled=false,changed_at=now(),reason='USER_KILL_SWITCH'`,[req.user.id]);const r=await cx.query(`DELETE FROM user_broker_tokens WHERE user_id=$1 RETURNING broker`,[req.user.id]);await cx.query(`INSERT INTO security_audit_log(user_id,event_type,request_id,details) VALUES($1,'KILL_SWITCH',$2,$3)`,[req.user.id,req.id,{deleted:r.rowCount}]);await cx.query('COMMIT');return{ok:true,deleted:r.rowCount};}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});

app.get('/api/v1/platform/demo',async(req:any)=>{const symbol=typeof req.query?.symbol==='string'&&/^[A-Z0-9-]{1,20}$/.test(req.query.symbol)?req.query.symbol:'NIFTY';const candles=syntheticCandles(symbol,260,23),features=engineerFeatures(candles),latest=features.at(-1)!,decision=classify(latest),risk=sizePosition(latest,decision.signal,defaultRisk),result=backtest(candles,defaultRisk);return{mode:'SIMULATION',exchange:'NSE',symbol,asOf:latest.time,market:{candles:candles.slice(-90),latest},decision:{...decision,risk},backtest:{...result,equityCurve:result.equityCurve.slice(-90),tradeLog:result.tradeLog.slice(-10)},walkForward:walkForward(candles,defaultRisk),portfolio:optimizePortfolio([.12,.09,.15,.07],[[.04,.01,.015,.005],[.01,.025,.012,.004],[.015,.012,.06,.01],[.005,.004,.01,.018]],2.5,3)};});

for(const [route,file] of [['/','public/login.html'],['/login','public/login.html'],['/create-account','public/create-account.html'],['/forgot-password','public/forgot-password.html'],['/account','public/account.html'],['/dashboard','public/dashboard.html']] as const){const html=readFileSync(join(process.cwd(),file),'utf8');app.get(route,async(_,reply)=>reply.type('text/html; charset=utf-8').send(html));}
setInterval(()=>void db.query(`DELETE FROM user_broker_tokens WHERE session_expiry_timestamp<=now()`),60000).unref();
app.get('/health/live',async()=>({ok:true}));
await app.listen({port:Number(process.env.PORT??3000),host:process.env.HOST??'127.0.0.1'});
