import 'dotenv/config';
import Fastify from 'fastify'; import cookie from '@fastify/cookie'; import helmet from '@fastify/helmet'; import rateLimit from '@fastify/rate-limit';
import pg from 'pg'; import { OAuth2Client } from 'google-auth-library'; import twilio from 'twilio'; import { fetch,ProxyAgent } from 'undici'; import { createHash } from 'node:crypto'; import { DateTime } from 'luxon';
import { security,Vault } from './security.js';

const required=['APP_ORIGIN','DATABASE_URL','COOKIE_SECRET','GOOGLE_CLIENT_ID','TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_VERIFY_SERVICE_SID','DATA_KEYRING_JSON','ACTIVE_DATA_KEY_VERSION','BROKER_CONFIG_JSON'] as const;
for(const key of required)if(!process.env[key])throw new Error(`Missing ${key}`);
const prod=process.env.NODE_ENV==='production';if(prod&&!process.env.BROKER_HTTPS_PROXY)throw new Error('Static-IP BROKER_HTTPS_PROXY required');
const origin=process.env.APP_ORIGIN!,db=new pg.Pool({connectionString:process.env.DATABASE_URL}),google=new OAuth2Client(process.env.GOOGLE_CLIENT_ID),sms=twilio(process.env.TWILIO_ACCOUNT_SID,process.env.TWILIO_AUTH_TOKEN);
const vault=new Vault(JSON.parse(process.env.DATA_KEYRING_JSON!),process.env.ACTIVE_DATA_KEY_VERSION!);const brokerConfigs=JSON.parse(process.env.BROKER_CONFIG_JSON!) as Record<string,{clientId:string;clientSecret:string;authorizeUrl:string;tokenUrl:string;scopes:string[]}>;
const dispatcher=process.env.BROKER_HTTPS_PROXY?new ProxyAgent(process.env.BROKER_HTTPS_PROXY):undefined;const app=Fastify({logger:{redact:['req.headers.authorization','req.headers.cookie','res.headers.set-cookie','body.credential','body.code','*.access_token','*.clientSecret','*.mobile']},bodyLimit:32768});
await app.register(helmet);await app.register(cookie,{secret:process.env.COOKIE_SECRET!});await app.register(rateLimit,{max:60,timeWindow:'1 minute'});
app.addHook('onRequest',async(req,reply)=>{if(prod&&['POST','PUT','PATCH','DELETE'].includes(req.method)&&req.headers.origin!==origin)return reply.code(403).send({error:'bad_origin'});});
const user=async(req:any,reply:any)=>{const signed=req.cookies.gnk_session;if(!signed)return reply.code(401).send({error:'authentication_required'});const raw=req.unsignCookie(signed);if(!raw.valid)return reply.code(401).send({error:'invalid_session'});const q=await db.query(`SELECT u.id,u.email,u.role FROM app_sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.revoked_at IS NULL AND s.expires_at>now()`,[security.sha256(raw.value)]);if(!q.rowCount)return reply.code(401).send({error:'invalid_session'});req.user=q.rows[0];};
async function session(id:string,reply:any){const raw=security.randomToken();await db.query(`INSERT INTO app_sessions(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '12 hours')`,[id,security.sha256(raw)]);reply.setCookie('gnk_session',raw,{httpOnly:true,secure:prod,sameSite:'lax',path:'/',signed:true,maxAge:43200});}

app.post('/api/v1/auth/google',async(req:any,reply)=>{const ticket=await google.verifyIdToken({idToken:req.body?.credential,audience:process.env.GOOGLE_CLIENT_ID});const p=ticket.getPayload();if(!p?.sub||!p.email||!p.email_verified)return reply.code(401).send({error:'unverified_identity'});const cx=await db.connect();try{await cx.query('BEGIN');let q=await cx.query(`SELECT user_id FROM user_identities WHERE kind='google' AND provider_subject=$1`,[p.sub]);let id=q.rows[0]?.user_id;if(!id){q=await cx.query(`SELECT id FROM users WHERE lower(email)=lower($1) FOR UPDATE`,[p.email]);id=q.rows[0]?.id??(await cx.query(`INSERT INTO users(email,display_name) VALUES($1,$2) RETURNING id`,[p.email,p.name])).rows[0].id;await cx.query(`INSERT INTO user_identities(user_id,kind,provider_subject,verified_at) VALUES($1,'google',$2,now())`,[id,p.sub]);}await cx.query('COMMIT');await session(id,reply);return{ok:true};}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});
const mobile=/^\+[1-9]\d{7,14}$/;
app.post('/api/v1/auth/otp/request',async(req:any,reply)=>{if(!mobile.test(req.body?.mobile))return reply.code(400).send({error:'invalid_mobile'});await sms.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID!).verifications.create({to:req.body.mobile,channel:'sms'});await db.query(`INSERT INTO otp_attempts(mobile_hash,expires_at) VALUES($1,now()+interval '10 minutes')`,[security.sha256(req.body.mobile)]);return reply.code(202).send({ok:true});});
app.post('/api/v1/auth/otp/verify',async(req:any,reply)=>{const {mobile:m,code}=req.body??{};if(!mobile.test(m)||!/^\d{4,10}$/.test(code))return reply.code(400).send({error:'invalid_input'});const a=await db.query(`UPDATE otp_attempts SET attempt_count=attempt_count+1 WHERE id=(SELECT id FROM otp_attempts WHERE mobile_hash=$1 AND consumed_at IS NULL AND expires_at>now() AND attempt_count<5 ORDER BY created_at DESC LIMIT 1 FOR UPDATE SKIP LOCKED) RETURNING id`,[security.sha256(m)]);if(!a.rowCount)return reply.code(429).send({error:'otp_unavailable'});const check=await sms.verify.v2.services(process.env.TWILIO_VERIFY_SERVICE_SID!).verificationChecks.create({to:m,code});if(check.status!=='approved')return reply.code(401).send({error:'invalid_otp'});const cx=await db.connect();try{await cx.query('BEGIN');let q=await cx.query(`SELECT user_id FROM user_identities WHERE kind='mobile' AND provider_subject=$1`,[m]);let id=q.rows[0]?.user_id;if(!id){id=(await cx.query(`INSERT INTO users DEFAULT VALUES RETURNING id`)).rows[0].id;await cx.query(`INSERT INTO user_identities(user_id,kind,provider_subject,verified_at) VALUES($1,'mobile',$2,now())`,[id,m]);}await cx.query(`UPDATE otp_attempts SET consumed_at=now() WHERE id=$1`,[a.rows[0].id]);await cx.query('COMMIT');await session(id,reply);return{ok:true};}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});
app.post('/api/v1/auth/logout',{preHandler:user},async(req:any,reply)=>{const raw=req.unsignCookie(req.cookies.gnk_session);if(raw.valid)await db.query(`UPDATE app_sessions SET revoked_at=now() WHERE token_hash=$1`,[security.sha256(raw.value)]);reply.clearCookie('gnk_session',{path:'/'});return{ok:true};});

const broker=(name:string)=>{if(!['dhan','fyers','zerodha','angelone','upstox'].includes(name)||!brokerConfigs[name])throw new Error('unsupported_or_disabled_broker');return brokerConfigs[name]!;};
app.get('/api/v1/auth/redirect/:broker',{preHandler:user},async(req:any,reply)=>{const name=req.params.broker,c=broker(name),state=security.randomToken();await db.query(`INSERT INTO broker_oauth_states(user_id,broker,state_hash,expires_at) VALUES($1,$2,$3,now()+interval '10 minutes')`,[req.user.id,name,security.sha256(state)]);const u=new URL(c.authorizeUrl);u.searchParams.set(name==='zerodha'?'api_key':'client_id',c.clientId);if(name==='zerodha')u.searchParams.set('redirect_params',new URLSearchParams({state}).toString());else{u.searchParams.set('redirect_uri',`${origin}/api/v1/auth/callback/${name}`);u.searchParams.set('response_type','code');u.searchParams.set('state',state);if(c.scopes?.length)u.searchParams.set('scope',c.scopes.join(' '));}return reply.redirect(u.toString());});
app.get('/api/v1/auth/callback/:broker',async(req:any,reply)=>{const name=req.params.broker,c=broker(name),state=req.query.state??new URLSearchParams(req.query.redirect_params??'').get('state'),code=name==='zerodha'?req.query.request_token:req.query.code;if(!state||!code)return reply.code(400).send({error:'invalid_callback'});const cx=await db.connect();try{await cx.query('BEGIN');const s=await cx.query(`UPDATE broker_oauth_states SET consumed_at=now() WHERE state_hash=$1 AND broker=$2 AND consumed_at IS NULL AND expires_at>now() RETURNING user_id`,[security.sha256(state),name]);if(!s.rowCount){await cx.query('ROLLBACK');return reply.code(400).send({error:'invalid_or_expired_state'});}const f=new URLSearchParams();if(name==='zerodha'){f.set('api_key',c.clientId);f.set('request_token',code);f.set('checksum',createHash('sha256').update(c.clientId+code+c.clientSecret).digest('hex'));}else{Object.entries({code,client_id:c.clientId,client_secret:c.clientSecret,redirect_uri:`${origin}/api/v1/auth/callback/${name}`,grant_type:'authorization_code'}).forEach(([k,v])=>f.set(k,v));}const response=await fetch(c.tokenUrl,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','accept':'application/json'},body:f,dispatcher});if(!response.ok)throw new Error(`broker_exchange_failed:${response.status}`);const raw:any=await response.json(),token=(raw.data??raw).access_token;if(typeof token!=='string')throw new Error('missing_access_token');const uid=s.rows[0].user_id,enc=vault.encrypt(token,`${uid}:${name}:access_token`);let expiry=DateTime.now().setZone('Asia/Kolkata').set({hour:15,minute:30,second:0,millisecond:0});if(expiry<=DateTime.now().setZone('Asia/Kolkata'))expiry=expiry.plus({days:1});await cx.query(`INSERT INTO user_broker_tokens(user_id,broker,client_id,encrypted_access_token,encryption_key_version,token_generated_at,session_expiry_timestamp) VALUES($1,$2,$3,$4,$5,now(),$6) ON CONFLICT(user_id,broker) DO UPDATE SET encrypted_access_token=excluded.encrypted_access_token,encryption_key_version=excluded.encryption_key_version,token_generated_at=now(),session_expiry_timestamp=excluded.session_expiry_timestamp,revoked_at=NULL,updated_at=now()`,[uid,name,c.clientId,enc.ciphertext,enc.keyVersion,expiry.toUTC().toJSDate()]);await cx.query('COMMIT');return reply.redirect(`${origin}/brokers?connected=${name}`);}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});
app.post('/api/v1/trades/kill-switch',{preHandler:user},async(req:any,reply)=>{if(req.body?.confirm!=='KILL')return reply.code(400).send({error:'confirmation_required'});const cx=await db.connect();try{await cx.query('BEGIN');await cx.query(`INSERT INTO trade_worker_state(user_id,enabled,reason) VALUES($1,false,'USER_KILL_SWITCH') ON CONFLICT(user_id) DO UPDATE SET enabled=false,changed_at=now(),reason='USER_KILL_SWITCH'`,[req.user.id]);const r=await cx.query(`DELETE FROM user_broker_tokens WHERE user_id=$1 RETURNING broker`,[req.user.id]);await cx.query(`INSERT INTO security_audit_log(user_id,event_type,request_id,details) VALUES($1,'KILL_SWITCH',$2,$3)`,[req.user.id,req.id,{deleted:r.rowCount}]);await cx.query('COMMIT');return{ok:true,deleted:r.rowCount};}catch(e){await cx.query('ROLLBACK');throw e;}finally{cx.release();}});
setInterval(()=>void db.query(`DELETE FROM user_broker_tokens WHERE session_expiry_timestamp<=now()`),60000).unref();app.get('/health/live',async()=>({ok:true}));await app.listen({port:Number(process.env.PORT??3000),host:'0.0.0.0'});
